### PR TITLE
Ports B.E.P.I.S

### PR DESCRIPTION
**Pull request by Neotwr**
## Changelog
:cl: Neotw, ArcaneMusic, Time-Green
add: The RnD department has been gifted a state-of-the-art new research tool, the B.E.P.I.S. by Nanotrasen's Venture Capital Labs, after repeatedly wasting all of their funds. Hopefully you'll find a... wiser use for it.
add: A new Tech Node can be unlocked through proper investment with the B.E.P.I.S.
add: In an unrelated piece of news, a deer was recently found to be the culprit of Nanotrasen Venture Capital Labs's onboard nuclear failsafe device detonating. Yes, we're sure it wasn't the Syndicate this time. Yes, we wish we were joking too.
fix: Fixes a small bug with tech disks containing hidden nodes not researching.
add: A new Technology has been implemented as a major reward in the B.E.P.I.S., Specialized Engineering, to appeal to engineering utility and new construction horizons.
tweak: Watchers will now actively consume diamond ore left lying around, alongside the new survival pens.
add: A new technology has been implemented into the B.E.P.I.S, Australicus Security Protocols, after our lab boys cracked open a cold one with those mates from a couple sectors south.
/:cl:

## About The Pull Request
Adds a new RnD method, the B.E.P.I.S
Read more here about the new items: https://github.com/tgstation/tgstation/pull/48040 https://github.com/tgstation/tgstation/pull/48507 https://github.com/tgstation/tgstation/pull/48600
~~https://github.com/tgstation/tgstation/pull/48606~~ removed

### CODE REVIEW

**Comment by Toxici11i** [comment]
-1 for the sheer fact its a /tg/ port AND it includes a bunch of other misc items, changes and most importantly rebalancing of existing items

**Comment by Nopm** [comment]
Why are /tg/ ports bad? Explain your reasoning better. 
Also, if it adds to the game instead of removing, then it's not going to be closed. Unlike /tg/ or other codebases, we're not worried about the game getting "bloated" or whatever you call it. The more features, the better.
The re-balancing can be certainly looked at, but I see no reason to deny this PR otherwise.

**Comment by Toxici11i** [comment]
> Why are /tg/ ports bad? Explain your reasoning better.
> Also, if it adds to the game instead of removing, then it's not going to be closed. Unlike /tg/ or other codebases, we're not worried about the game getting "bloated" or whatever you call it. The more features, the better.
> The re-balancing can be certainly looked at, but I see no reason to deny this PR otherwise.

the exact reason /tg/ ports are bad is because instead of just adding features, they see to rebalancing and/or changing major functions of other items. This makes them a pain in the ass to port, even when cherrypicking.

Otherwise, the BEPIS would be a good addition, yet even at a glance I can see changes to items like the rapid series of devices etc.

**Comment by Toxici11i** [comment]
Ok deffo no now. Extreme surgeries are batshit overpowered, even when compared to hippies forge. You can literally polymorph people with it, and with cloning being ez, you can spam it all you want.

neo why

**Pull request merged**
