### PR TITLE
The Opaopapanerd Statue

### PR DESCRIPTION
**Pull request by g-ramalho**
## About

Adds the opao statue in memory of our fallen heroes

## Changelog
:cl:
add: Apud memoriae de...
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
I think you forgot to commit the code???

**Comment by SrPiwin** [comment]
oof

**Review by ghost — CHANGES_REQUESTED** [review]
Great code, you just forgot the code. That's it.

**Comment by g-ramalho** [comment]
``

**Pull request closed without merging**
